GET http://localhost:3000/items

###

GET http://localhost:3000/items/3

###

POST http://localhost:3000/items

###

PUT http://localhost:3000/books/${id}

###

DELETE http://localhost:3000/books/${id}
